# Generated by Django 4.2.30 on 2026-07-25 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('was_detected', models.BooleanField(default=False)),
                ('input_mode', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=16)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_lang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='source_translations', to='core.language')),
                ('target_lang', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='target_translations', to='core.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_transl_user_id_36bf13_idx')],
            },
        ),
    ]
