# Generated by Django 4.2.30 on 2026-07-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='input_mode',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('document', 'Document')], default='text', max_length=16),
        ),
    ]
