# Generated by Django 4.2.30 on 2026-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_input_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='document_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
